version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_vault_app
    restart: always
    environment:
      PORT: 8082
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    ports:
      - "8082:8082"
      - "40000:40000"  # Exposing the Delve debug port
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: